name: CI Pipeline

on:
  workflow_dispatch:  # hand run

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-backend-image .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image (again, for test)
        run: docker build -t my-backend-image .

      - name: Run Pytest
        run: docker run --rm my-backend-image pytest -s -v

  deploy:
    name: Deploy with Docker Compose (на EC2)
    runs-on: self-hosted  #<--------
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest code
        run: git pull origin main

      - name: Rebuild and restart containers
        run: |
          docker compose down
          docker compose up -d --build
